<a href="https://colab.research.google.com/github/yakaralar/IE492/blob/master/meta_brute_tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·
Mounted at /content/drive

In [0]:
import os
import glob
import shutil
os.listdir()

['.config',
 'RealTimeConsumption_holiday.csv',
 'RealTimeConsumption-01122014-09032020.csv',
 'RealTimeConsumption_unholidayized.csv',
 'drive',
 'HW_preds_erdem.csv',
 'sample_data']

In [0]:
os.listdir("drive/My Drive/colab_datas/IE 492")

['Comparison of methods.pdf',
 '1-s2.0-S1364032114000914-main.pdf',
 '1-s2.0-S0360544209002539-main.pdf',
 '1-s2.0-S1876610211043116-main.pdf',
 '1-s2.0-S0305048311001423-main.pdf',
 'weather_turkey_processed.zip',
 'Meta_L_makaleler',
 'all_data.feather',
 'UECM-15012015-20022020.csv',
 'RealTimeConsumption-01122014-09032020.csv',
 'updated_support-date_based_information.r',
 'ozel_gunler',
 'RealTimeConsumption_unholidayized.csv',
 'RealTimeConsumption_unhol_decomposed.csv',
 'RealTimeConsumption_holiday.csv',
 'HW_preds.csv',
 'kubi_preds']

In [0]:
shutil.copy("drive/My Drive/colab_datas/IE 492/RealTimeConsumption_unholidayized.csv","./")
shutil.copy("drive/My Drive/colab_datas/IE 492/RealTimeConsumption-01122014-09032020.csv","./")
shutil.copy("drive/My Drive/colab_datas/IE 492/RealTimeConsumption_holiday.csv","./")

'./RealTimeConsumption_holiday.csv'

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas_profiling
%matplotlib inline
from tqdm import tqdm_notebook as tqdm

# Consumption df

In [0]:
# # bruuuuuuuh
# cons_holiday_binary=pd.read_csv("RealTimeConsumption_holiday.csv",encoding='latin-1')
# cons_holiday_binary["Datetime"]=cons_holiday_binary["Date"]+" "+cons_holiday_binary["Hour"]
# cons_holiday_binary["Datetime"]=pd.to_datetime(cons_holiday_binary["Datetime"],format="%d.%m.%Y %H:%M")
# cons_holiday_binary.head()

In [0]:
# validattion_predictions=
preds_paths=glob.glob("drive/My Drive/colab_datas/IE 492/kubi_preds/*.csv")
preds_paths

['drive/My Drive/colab_datas/IE 492/kubi_preds/LR_2.csv',
 'drive/My Drive/colab_datas/IE 492/kubi_preds/naive_2.csv',
 'drive/My Drive/colab_datas/IE 492/kubi_preds/LR_2_7_w_dates.csv',
 'drive/My Drive/colab_datas/IE 492/kubi_preds/naive_7.csv',
 'drive/My Drive/colab_datas/IE 492/kubi_preds/LR_2_7.csv',
 'drive/My Drive/colab_datas/IE 492/kubi_preds/LR_7.csv',
 'drive/My Drive/colab_datas/IE 492/kubi_preds/HW_preds_erdem.csv',
 'drive/My Drive/colab_datas/IE 492/kubi_preds/Cat2_categorical.csv',
 'drive/My Drive/colab_datas/IE 492/kubi_preds/Cat1.csv']

In [0]:
# a=pd.read_csv("drive/My Drive/colab_datas/IE 492/kubi_preds/HW_preds_erdem.csv")
# a["Datetime"]=pd.to_datetime(a["Datetime"])
# a.loc[a["Datetime"]>=pd.to_datetime("2019-02-01 00:00:00")][["Datetime","HW_unhol_reg"]].to_csv("drive/My Drive/colab_datas/IE 492/kubi_preds/HW_preds_erdem.csv",index=False)

In [0]:
pred_dfs=[]
for path_ in preds_paths:
    pred_dfs.append(pd.read_csv(path_))
preds=pd.concat(pred_dfs,axis=1)
preds

                 Datetime    LR_2_preds  ...         Cat1          Datetime
0     2019-02-01 00:00:00  31744.801869  ...  31356.34841  02/01/2019 00:00
1     2019-02-01 01:00:00  30353.806407  ...  29271.55776  02/01/2019 01:00
2     2019-02-01 02:00:00  29429.213104  ...  27938.26896  02/01/2019 02:00
3     2019-02-01 03:00:00  28904.205359  ...  27042.40179  02/01/2019 03:00
4     2019-02-01 04:00:00  28714.921348  ...  27099.29248  02/01/2019 04:00
...                   ...           ...  ...          ...               ...
9523  2020-03-03 19:00:00  34433.450000  ...  37482.70916  03/03/2020 19:00
9524  2020-03-03 20:00:00  34324.041524  ...  36819.23862  03/03/2020 20:00
9525  2020-03-03 21:00:00  33821.654912  ...  36119.32012  03/03/2020 21:00
9526  2020-03-03 22:00:00  33102.945835  ...  35157.30226  03/03/2020 22:00
9527  2020-03-03 23:00:00  32035.951504  ...  33648.94634  03/03/2020 23:00

[9528 rows x 18 columns]

In [0]:
preds=preds[["Datetime"]+preds.columns.difference(["Datetime"]).tolist()]
preds=preds.iloc[:,8:]

In [0]:
preds

              Datetime         Cat1  ...    LR_2_preds    LR_7_preds
0     02/01/2019 00:00  31356.34841  ...  31744.801869  32126.739766
1     02/01/2019 01:00  29271.55776  ...  30353.806407  30503.032726
2     02/01/2019 02:00  27938.26896  ...  29429.213104  29337.249341
3     02/01/2019 03:00  27042.40179  ...  28904.205359  28681.681110
4     02/01/2019 04:00  27099.29248  ...  28714.921348  28550.613245
...                ...          ...  ...           ...           ...
9523  03/03/2020 19:00  37482.70916  ...  34433.450000  38283.936762
9524  03/03/2020 20:00  36819.23862  ...  34324.041524  37866.571236
9525  03/03/2020 21:00  36119.32012  ...  33821.654912  36847.073493
9526  03/03/2020 22:00  35157.30226  ...  33102.945835  35746.459492
9527  03/03/2020 23:00  33648.94634  ...  32035.951504  34296.269012

[9528 rows x 10 columns]

In [0]:
# bruuuuuuuh
cons_holiday_binary=pd.read_csv("RealTimeConsumption_holiday.csv",encoding='latin-1')
cons_holiday_binary["Datetime"]=cons_holiday_binary["Date"]+" "+cons_holiday_binary["Hour"]
cons_holiday_binary["Datetime"]=pd.to_datetime(cons_holiday_binary["Datetime"],format="%d.%m.%Y %H:%M")
cons_holiday_binary.head()

         Date   Hour  ...  is_yilbasioncesi is_zaferbayrami
0  31.12.2015  00:00  ...                 1               0
1  31.12.2015  01:00  ...                 1               0
2  31.12.2015  02:00  ...                 1               0
3  31.12.2015  03:00  ...                 1               0
4  31.12.2015  04:00  ...                 1               0

[5 rows x 43 columns]

In [0]:
preds["reel"]=cons_holiday_binary.loc[cons_holiday_binary["Datetime"]>=pd.to_datetime("2019-02-01 00:00:00")][["Consumption"]].values
preds.Datetime=pd.to_datetime(preds.Datetime)
preds

                Datetime         Cat1  ...    LR_7_preds      reel
0    2019-02-01 00:00:00  31356.34841  ...  32126.739766  31878.29
1    2019-02-01 01:00:00  29271.55776  ...  30503.032726  30064.08
2    2019-02-01 02:00:00  27938.26896  ...  29337.249341  28813.77
3    2019-02-01 03:00:00  27042.40179  ...  28681.681110  27865.76
4    2019-02-01 04:00:00  27099.29248  ...  28550.613245  27554.48
...                  ...          ...  ...           ...       ...
9523 2020-03-03 19:00:00  37482.70916  ...  38283.936762  37936.79
9524 2020-03-03 20:00:00  36819.23862  ...  37866.571236  37553.37
9525 2020-03-03 21:00:00  36119.32012  ...  36847.073493  36581.73
9526 2020-03-03 22:00:00  35157.30226  ...  35746.459492  35434.36
9527 2020-03-03 23:00:00  33648.94634  ...  34296.269012  33827.00

[9528 rows x 11 columns]

In [0]:
def mean_absolute_percentage_error(y_true, y_pred): 
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

In [0]:
## 5 iq move dÃ¼zelt bunu
best_models=[]
for i,row in preds.iterrows():
    best_mape=999999
    best_model=""
    for col in preds.columns.difference(["Datetime","reel"]):
        mape_=mean_absolute_percentage_error(row["reel"],row[col])
        if best_mape>mape_:
            best_mape=mape_
            best_model=col
    best_models.append(best_model)
preds["best_model"]=best_models
len(preds)+1

9529

In [0]:
preds

                Datetime         Cat1  ...      reel            best_model
0    2019-02-01 00:00:00  31356.34841  ...  31878.29          LR_2_7_preds
1    2019-02-01 01:00:00  29271.55776  ...  30064.08          LR_2_7_preds
2    2019-02-01 02:00:00  27938.26896  ...  28813.77          LR_2_7_preds
3    2019-02-01 03:00:00  27042.40179  ...  27865.76  LR_2_7_w_dates_preds
4    2019-02-01 04:00:00  27099.29248  ...  27554.48  LR_2_7_w_dates_preds
...                  ...          ...  ...       ...                   ...
9523 2020-03-03 19:00:00  37482.70916  ...  37936.79      Cat2_categorical
9524 2020-03-03 20:00:00  36819.23862  ...  37553.37      Cat2_categorical
9525 2020-03-03 21:00:00  36119.32012  ...  36581.73      Cat2_categorical
9526 2020-03-03 22:00:00  35157.30226  ...  35434.36          LR_2_7_preds
9527 2020-03-03 23:00:00  33648.94634  ...  33827.00                  Cat1

[9528 rows x 12 columns]

In [0]:
shift_timespan=5*24
chosen_models=["unknown"]*shift_timespan
for i in tqdm(range(shift_timespan,len(preds))):
    ## buraya prob koyacaggÄ±z
    chosen_models.append(preds["best_model"].iloc[i-shift_timespan:i].value_counts().index[0])
preds["chosen"]=chosen_models

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  This is separate from the ipykernel package so we can avoid doing imports until

HBox(children=(IntProgress(value=0, max=9408), HTML(value='')))

In [0]:
mapes=preds.loc[preds["chosen"]!="unknown"].apply(lambda x: mean_absolute_percentage_error(x["reel"],x[x["chosen"]]),axis=1)
mapes.mean()

4.122311739376671

In [0]:
mapes.sort_values()

2789     0.001206
6151     0.003082
5489     0.003461
2481     0.003525
3571     0.004497
          ...
4597    61.186497
4599    61.975775
4598    65.684021
4596    66.219791
4595    76.310461
Length: 9408, dtype: float64

In [0]:
preds.iloc[2963]

Datetime                 2019-06-04 11:00:00
Cat1                                 28796.5
Cat2_categorical                     28515.8
Consumption_2_lag                    28188.4
Consumption_7_lag                    35793.6
HW_unhol_reg                     5.18131e+07
LR_2_7_preds                         33250.2
LR_2_7_w_dates_preds                 20086.1
LR_2_preds                           29339.9
LR_7_preds                           35325.1
reel                                 19946.3
best_model              LR_2_7_w_dates_preds
chosen                  LR_2_7_w_dates_preds
Name: 2963, dtype: object

In [0]:
preds.apply(lambda x: mean_absolute_percentage_error(x["reel"],x[x["best_model"]]),axis=1).mean()

1.3421242368923265

In [0]:
cons_holiday_binary

             Date   Hour  ...  is_yilbasioncesi is_zaferbayrami
0      31.12.2015  00:00  ...                 1               0
1      31.12.2015  01:00  ...                 1               0
2      31.12.2015  02:00  ...                 1               0
3      31.12.2015  03:00  ...                 1               0
4      31.12.2015  04:00  ...                 1               0
...           ...    ...  ...               ...             ...
36571  03.03.2020  19:00  ...                 0               0
36572  03.03.2020  20:00  ...                 0               0
36573  03.03.2020  21:00  ...                 0               0
36574  03.03.2020  22:00  ...                 0               0
36575  03.03.2020  23:00  ...                 0               0

[36576 rows x 43 columns]

In [0]:
cat_df_1=cons_holiday_binary[["Datetime"] + [i for i in cons_holiday_binary.columns if i.startswith("is_")]].copy()
cat_df_1["Hour"]=cat_df_1["Datetime"].apply(lambda x:x.hour).astype(int)
cat_df_1["Day"]=cat_df_1["Datetime"].apply(lambda x:x.day).astype(int)
cat_df_1["Month"]=cat_df_1["Datetime"].apply(lambda x:x.month).astype(int)
cat_df_1["weekday"]=cat_df_1["Datetime"].apply(lambda x: x.weekday()).astype(int)

## decision tree

In [0]:
from sklearn.tree import DecisionTreeClassifier

shift_timespan=30*24
predicted_model=["unknown"]*shift_timespan
for i in tqdm(range(shift_timespan,len(preds))):
    train_df=preds[["Datetime","best_model"]].iloc[:i+1]
    train_df=pd.merge(train_df,cat_df_1,how="left",on="Datetime")
    valid_df=train_df.iloc[-1]
    train_df=train_df.iloc[:i]
    tree=DecisionTreeClassifier()
    tree.fit(train_df.drop(columns=["best_model","Datetime"]),train_df["best_model"])
    # random forestt rreggrressor
    pred=tree.predict(pd.DataFrame(valid_df).T.drop(columns=["best_model","Datetime"]))
    # predict proba
    predicted_model.append(pred[0])
preds["tree_predicted"]=predicted_model
preds

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  """

HBox(children=(IntProgress(value=0, max=8808), HTML(value='')))

                Datetime         Cat1  ...   chosen        tree_predicted
0    2019-02-01 00:00:00  31356.34841  ...  unknown               unknown
1    2019-02-01 01:00:00  29271.55776  ...  unknown               unknown
2    2019-02-01 02:00:00  27938.26896  ...  unknown               unknown
3    2019-02-01 03:00:00  27042.40179  ...  unknown               unknown
4    2019-02-01 04:00:00  27099.29248  ...  unknown               unknown
...                  ...          ...  ...      ...                   ...
9523 2020-03-03 19:00:00  37482.70916  ...     Cat1  LR_2_7_w_dates_preds
9524 2020-03-03 20:00:00  36819.23862  ...     Cat1      Cat2_categorical
9525 2020-03-03 21:00:00  36119.32012  ...     Cat1      Cat2_categorical
9526 2020-03-03 22:00:00  35157.30226  ...     Cat1      Cat2_categorical
9527 2020-03-03 23:00:00  33648.94634  ...     Cat1          LR_2_7_preds

[9528 rows x 14 columns]

In [0]:
mapes=preds.loc[preds["tree_predicted"]!="unknown"].apply(lambda x: mean_absolute_percentage_error(x["reel"],x[x["tree_predicted"]]),axis=1)
mapes.mean()

2.1955688210731803

In [0]:
mapes.sort_values()

764      0.000143
7703     0.000400
1654     0.000509
6822     0.000782
8654     0.000923
          ...
5264    35.104765
8027    42.839706
2977    43.296812
8024    48.721586
4592    56.841203
Length: 8808, dtype: float64

In [0]:
preds.iloc[[2976,2978]]

                Datetime  ...        tree_predicted
2976 2019-06-05 00:00:00  ...            LR_2_preds
2978 2019-06-05 02:00:00  ...  LR_2_7_w_dates_preds

[2 rows x 14 columns]